//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class SICMST2Entities : DbContext
{
    public SICMST2Entities()
        : base("name=SICMST2Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Autobuses> Autobuses { get; set; }
    public virtual DbSet<AutobusesKmFueraServicio> AutobusesKmFueraServicio { get; set; }
    public virtual DbSet<AutobusesKmServicio> AutobusesKmServicio { get; set; }
    public virtual DbSet<AutobusesTurnos_> AutobusesTurnos_ { get; set; }
    public virtual DbSet<Cajeros> Cajeros { get; set; }
    public virtual DbSet<Ciudades> Ciudades { get; set; }
    public virtual DbSet<ClaseTarjeta> ClaseTarjeta { get; set; }
    public virtual DbSet<Concesiones> Concesiones { get; set; }
    public virtual DbSet<dCobroEfectivo> dCobroEfectivo { get; set; }
    public virtual DbSet<dCobroPrepago> dCobroPrepago { get; set; }
    public virtual DbSet<DiasFestivos> DiasFestivos { get; set; }
    public virtual DbSet<Dispositivos> Dispositivos { get; set; }
    public virtual DbSet<Documentos> Documentos { get; set; }
    public virtual DbSet<DocumentosCategoria> DocumentosCategoria { get; set; }
    public virtual DbSet<dPrepagoCajeros> dPrepagoCajeros { get; set; }
    public virtual DbSet<dPrepagoEstablecimientos> dPrepagoEstablecimientos { get; set; }
    public virtual DbSet<dPrepagoRedRecarga> dPrepagoRedRecarga { get; set; }
    public virtual DbSet<Empresas> Empresas { get; set; }
    public virtual DbSet<EmpresasTipo> EmpresasTipo { get; set; }
    public virtual DbSet<Fideicomisos> Fideicomisos { get; set; }
    public virtual DbSet<FideicomisosEmpresas> FideicomisosEmpresas { get; set; }
    public virtual DbSet<GrupoDispositivos> GrupoDispositivos { get; set; }
    public virtual DbSet<OperacionesRecaudo> OperacionesRecaudo { get; set; }
    public virtual DbSet<OperacionesRecaudoClase> OperacionesRecaudoClase { get; set; }
    public virtual DbSet<OperacionesRecaudoTipo> OperacionesRecaudoTipo { get; set; }
    public virtual DbSet<OrdenesEntrada> OrdenesEntrada { get; set; }
    public virtual DbSet<OrdenesEntradaCanceladas> OrdenesEntradaCanceladas { get; set; }
    public virtual DbSet<OrdenesEntradaDetalle> OrdenesEntradaDetalle { get; set; }
    public virtual DbSet<OrdenesEntradaEstatus> OrdenesEntradaEstatus { get; set; }
    public virtual DbSet<OrdenesEntradaTipo> OrdenesEntradaTipo { get; set; }
    public virtual DbSet<OrdenesPago> OrdenesPago { get; set; }
    public virtual DbSet<OrdenesPagoCanceladas> OrdenesPagoCanceladas { get; set; }
    public virtual DbSet<OrdenesPagoDetalle> OrdenesPagoDetalle { get; set; }
    public virtual DbSet<OrdenesPagoEstatus> OrdenesPagoEstatus { get; set; }
    public virtual DbSet<OrdenesPagoPagos> OrdenesPagoPagos { get; set; }
    public virtual DbSet<OrdenesPagoTipo> OrdenesPagoTipo { get; set; }
    public virtual DbSet<Parabuses> Parabuses { get; set; }
    public virtual DbSet<POS> POS { get; set; }
    public virtual DbSet<PosTipo> PosTipo { get; set; }
    public virtual DbSet<Propietarios> Propietarios { get; set; }
    public virtual DbSet<PuntosControl> PuntosControl { get; set; }
    public virtual DbSet<RedRecarga> RedRecarga { get; set; }
    public virtual DbSet<Roles> Roles { get; set; }
    public virtual DbSet<Rutas> Rutas { get; set; }
    public virtual DbSet<Tarjetas> Tarjetas { get; set; }
    public virtual DbSet<TarjetasUsuarios> TarjetasUsuarios { get; set; }
    public virtual DbSet<TipoEquipos> TipoEquipos { get; set; }
    public virtual DbSet<Usuarios> Usuarios { get; set; }
    public virtual DbSet<UsuarioTransporte> UsuarioTransporte { get; set; }
}
