//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesPago
    {
        public long IdOrdenPago { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Fideicomiso { get; set; }
        public string Concepto { get; set; }
        public int Estatus { get; set; }
        public decimal Importe { get; set; }
        public Nullable<System.DateTime> FechaIni { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<int> UsuarioAprobacion { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public Nullable<int> UsuarioAutorizacion { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> UsuarioPago { get; set; }
        public Nullable<System.DateTime> FechaRegistroMasAntiguo { get; set; }
    }
}
